version: "3.9"
services:
  app1:
    build: .
    ports:
      - "8080:8080"
  app2:
    build: .
    ports:
      - "8081:8080"
  prometheus:
    image: prom/prometheus:v2.31.0
    ports:
      - "9090:9090"
    links:
      - app1
      - app2
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana:8.2.2
    ports:
      - "3000:3000"
    links:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./config/grafana/:/etc/grafana/provisioning:ro
volumes:
  grafana-storage: